### PR TITLE
Update travis ci infrastructure

### PR DESCRIPTION
**Pull request by ne0fhyk**

### CODE REVIEW

**Comment by ne0fhyk** [comment]
@squilter can you take a look at why this is failing the travis build.

**Comment by ne0fhyk** [comment]
@squilter here's the link to the migrating docs: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by squilter** [comment]
I can't figure it out.  The ServiceApp preDexDebug is failing.  I'm not sure what to do about that.  I get the same error when I run the project from the command line.

Maybe instead of running `./gradlew assembleDebug`, we just run `./gradlew build`, which works.

**Comment by ne0fhyk** [comment]
@squilter will make the change and test it.

**Pull request merged**
