### PR TITLE
Create Do Land Start point  

### PR DESCRIPTION
**Pull request by daimonkor**
DO_LAND_START mission item acts as a marker for the start of a landing
sequence. It is required for RTL auto landing (RTL_AUTOLAND != 0).

See http://plane.ardupilot.com/wiki/flying/automatic-landing/#using_do_land_start

Want merge to develop

### CODE REVIEW

**Comment by mrpollo** [comment]
was this branch rebased?, why are there so many merge commits?

**Comment by vvv** [comment]
@mrpollo: Lemme check...

**Comment by vvv** [comment]
@mrpollo: I have misled @daimonkor by proposing to create feature branch from master.

```
      C---D---E---F develop
     /
A---B---G---H---I master
                 \
                  J---K---L do_land_start
```

Merge to `develop` was doomed to be ugly:

```
      C---D---E---F-----------M develop
     /                       /
A---B---G---H---I master    /
                 \         /
                  J---K---L do_land_start

**Comment by mrpollo** [comment]
glad you could figured it out

**Comment by vvv** [comment]
Thanks for your vigilance!

**Pull request closed without merging**
