### PR TITLE
Add guide for Tower-Pebble

### PR DESCRIPTION
**Pull request by squilter**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@ne0fhyk Looks really good overall and the code is clear. I would have liked to see a bit more about the Pebble app code

There are some layout issues and a few minor comments listed below. I have not yet tried out the instructions but I have little doubt they will work. 

I don't know how to submit updates to an unmerged request - OK to just create comments as below? If you know of any good instructions on how to do such a merge let me know - will be helpful for next time.

Comments:

1. "In this example, we will learn about the Tower Pebble watchapp and companion app." - change to "... Tower Pebble watchapp and Android companion app". Link both of these app names to their google play store entries.

2. The first image (project selection) should be reduced in size. Generally you want images that are just big enough to read and understand - so that you can quickly get to the next content. There is a :width: attribute that can do this. 

3. "We need to clone the Github repository at DroidPlanner/Tower-Pebble" - generally I like to link to Github repos (master branch) when I refer to them. 

4. ", then click next.". The button says "OK". Generally I would mark this button press in bold ("then click **OK**")

5. "The code consists of two parts: the watchapp and the Android app." might be better as "*Tower Pebble* consists of two parts: the Watchapp and a companion Android app."

6. The architecture image (towerpebble_setup_2.png) is excellent to have. The image doesn't quite work for me - I looked at it before I read the explanation and I didn't think "watch app talking to android app". I think maybe renaming the android side to "Tower Pebble Android App" would help (and maybe also making the "Phone" border a lightly dotted line so that it is clear that this isn't actually what you'd see on a phone. @ne0fhyk - maybe we could get some graphics support for this?

In an ideal world you'd have just one image here, which would have the watchapp side of easy enough to read that you would no longer need the following image

7. For pebble  "We won’t delve into how that code works, " - why not? That's interesting too. Minimally some links to the information on developing Pebble apps?

8. The pebble image could probably be shrunk a little (towerpebble_setup_3.png)

9. The bullet lists in this section have inconsistent full stop terminators. All lists should pretty much adopt the same style, doesn't matter what it is. I prefer to start list with a colon and use no full stops.

10. The headings "1. Handling Requests" and "2. Sending Mode and Telemetry" are sub-headings. Remove the numbers from the headings, and replace the underline of === with an underline of ----

11. "The Android app looks like this:", "But that’s not important. - perhaps "A screenshot of the Android app is shown below. This app runs in the background and is used to connect the ....."

12. Shrink the Android app image (towerpebble_setup_4.png)

13. "PebbleCommunicatorService is automatically started up when a connection is established. This works because the AndroidManifest.xml has the following:" - mark up PebbleCommunicatorService and 
AndroidManifest.xml

14. "and the GCSEventsReceiver class will start the PebbleCommunicatorService like so:" - mark up the code entities. Actually, just go through and mark them all up :-)

15. "following method gets called (which handles the request):" to "following method gets called to handle the request:"

16. Pebble gets referred to a lot with inconsistent case - should be capitalised.

17. "are changing constantly, but it’s not critical that they are updated too frequently." - what do you mean - "are changing constantly, but it’s not critical that they are updated frequently." OR "are changing constantly, but it’s critical that they are not updated too frequently."?

18.
The code blocks in the bullets in "Sending Mode and Telemetry" need to be indented. This is a case where Sphinx is limited (the bullet needs to start with text). In any case, move the preceding line to actually appear above each of the points.

```
1. ``PebbleCommunicatorService`` needs to implement ``DroneListener``:

   .. code-block:: java

       public class PebbleCommunicatorService extends Service implements DroneListener, Towerlistener{

2. The DroneListener needs to be registered
```

Consistency/Style guide
==================
This document is fairly consistent in its use of markup. However it is not completely consistent with the rest of the documentation. I don't think you need to worry abut this now, but probably we need to define a documentation standard. Some thoughts

1. This doesn't mark up tool/program names names - I quite like to use italic for that - so  *Android Studio*. The sphinx way to do this markup is to use :program:`Android Studio` (there is [other interesting semantic markup here](http://sphinx-doc.org/markup/inline.html#other-semantic-markup) )
2. I quite like the bold to mark up file names. The sphinx way is to use :file:`build.gradle`
3. This marks up "menu options" using this style: **File>Import Project**. I like the bold, but I personally prefer **File | Import Project** 
4. All code items in text should be marked up using monotype
5. Ideally code items inline in text should be linked to their reference, though that is hard since the reference is not in Sphinx format.

Anyway, thats it for me. Nice job @squilter !

**Comment by ne0fhyk** [comment]
@hamishwillee the only way I'm aware of is to fork the branch making the pull request, and submit a pull request to it with the correction. As you did, I typically just comment alongside the code, and let it up to the dev to incorporate the comments.

To do so though, it's usually best to use the `file changed` tab, and link the comments directly to the target line ( a `+` icon shows up as you hover next to the changes).

**Comment by ne0fhyk** [comment]
@squilter Great job! Once you incorporate @hamishwillee's comments, it should be ready for inclusion.

@hamishwillee it could be worth to have a blog on diydrones to highlight @squilter work!

**Comment by hamishwillee** [comment]
@ne0fhyk - thanks for the advice

@squilter - I'd love to write a blog on this. Could you email me more information about you, your interest in drones, and your interest/engagement with this app? I'm hamish at 3drobotics dot com.

**Comment by squilter** [comment]
@hamishwillee Thanks for the comments!

I've got finals next week, so I probably won't have time to get around to this until the week after that.

**Comment by squilter** [comment]
@hamishwillee Okay, I've fixed most of them.  I did not do these yet:

6 @ne0fhyk Can you find somebody to help make this graphic?  My MS Paint skills aren't good enough.
7 I can maybe write some more here some other day.
9 Which lists, and what is a full stop terminator?
---
4. What is monotype, and how do I make it?

**Comment by hamishwillee** [comment]
Hi @squilter 

Thanks!
6. We can live without this updated for now (I not a barrier to acceptance)
7. OK, still useful without it, just "desirable"
9. Basically a fullstop at the end of the list - like this. If you look at this list here, some items have full stops and some don't. The list should be consistent.
4. Monotype just means "code style" - use two back ticks code items

**Comment by squilter** [comment]
I fixed the fullstops and added some explanation of the watchapp code.  I think all that's missing now is an improved graphic.

**Comment by hamishwillee** [comment]
@squilter I've only given it a quick scan, but on the face of it looks great. Thanks very much. 

@ne0fhyk This is ready IMO to push live (the current image could be improved, but if we can't resource it, then it is "good enough".

**Comment by ne0fhyk** [comment]
Sounds good!

**Comment by hamishwillee** [comment]
@ne0fhyk When should this appear on the live documentation?

**Comment by ne0fhyk** [comment]
Upon the next release of 3DR services. It'll then be merged into the master
branch from which the live documentation is generated.

--
Fredia Huya-Kouadio
Android Tech Lead, 3D Robotics
fredia@3dr.com

**Pull request merged**
